SnowflakePowered/snowflake

Snowflake.Tests/Controller/ControllerProfileTests.cs
Snowflake.Tests/Snowflake.Tests.csproj

Add tests that test Controller parsing

Tests: Add controller tests

---

Snowflake.API/Utility/FileHash.cs
Snowflake.Tests/Game/GameInfoTests.cs
Snowflake.Tests/Scraper/GameImagesResultTests.cs
Snowflake.Tests/Snowflake.Tests.csproj
Snowflake.Tests/Utility/BiDictionaryTests.cs
Snowflake.Tests/Utility/HashTests.cs

This adds tests for 
* BiDictionary
* GameInfo
* GameImagesResult
* FileHash

Tests: Add a variety of tests

---

Snowflake.API/Service/HttpServer/BaseHttpServer.cs
Snowflake.Tests/Service/HttpServer/BaseHttpServerTests.cs
Snowflake.Tests/Snowflake.Tests.csproj
Snowflake.Tests/packages.config

I'm not exactly sure if the security settings on the CI frameworks will allow these tests to pass. If they do, then merge this.

Tests: Test BaseHttpServer

---

NOTICE

Adds me to the notice file properly and spells out a rough format on how to do it.

Legal: Append @ronnchyran to the notice file as per PR #33

---

CONTRIBUTING.md

Create a CONTRIBUTING.md to sort out guidelines for contributions and contributors

Legal: Create Contribution guidelines.

---

Snowflake.API/Snowflake.API.csproj
Snowflake.API/packages.config
Snowflake.Core.Init/Form1.cs
Snowflake.Core.Init/Snowflake.Core.Init.csproj
Snowflake.Core.Init/packages.config
Snowflake.Service/Service/ScrapeService.cs
Snowflake.Service/Snowflake.Service.csproj
Snowflake.Service/packages.config
Snowflake.StandardAjax/Properties/AssemblyInfo.cs
Snowflake.StandardAjax/Snowflake.StandardAjax.csproj
Snowflake.StandardAjax/StandardAjax.Controller.cs
Snowflake.StandardAjax/StandardAjax.Game.cs
Snowflake.StandardAjax/StandardAjax.Platform.cs
Snowflake.StandardAjax/StandardAjax.cs
Snowflake.StandardAjax/resource/plugin.json
Snowflake.sln
Snowflake/Snowflake.csproj
Snowflake/packages.config

Removes the DuoVia.FuzzyString and ShortGuid dependencies on projects that don't require them.

Build: Remove unnecessary dependencies

---

.travis.yml

Adds a webhook so fure-kun hubot is notified upon build

Build-Travis: Add fure-kun webhook

---

Snowflake.API/Ajax/AjaxMethodParameterAttribute.cs
Snowflake.API/Ajax/IJSResponse.cs
Snowflake.API/Service/IScrapeService.cs
Snowflake.API/Snowflake.API.csproj
Snowflake.API/Utility/StringEncode.cs
Snowflake.Core.Init/Form1.cs
Snowflake.Service/Extensions/PlatformExts.cs
Snowflake.Service/Service/CoreService.cs
Snowflake.Service/Service/Manager/AjaxManager.cs
Snowflake.Service/Service/Manager/PluginManager.cs
Snowflake.Service/Service/ScrapeService.cs
Snowflake.StandardAjax/Properties/AssemblyInfo.cs
Snowflake.StandardAjax/Snowflake.StandardAjax.csproj
Snowflake.StandardAjax/StandardAjax.Controller.cs
Snowflake.StandardAjax/StandardAjax.Game.cs
Snowflake.StandardAjax/StandardAjax.Platform.cs
Snowflake.StandardAjax/StandardAjax.System.cs
Snowflake.StandardAjax/StandardAjax.cs
Snowflake.StandardAjax/packages.config
Snowflake.StandardAjax/resource/plugin.json
Snowflake.Tests/Fakes/FakeJSResponse.cs
Snowflake.sln
Snowflake/Ajax/BaseAjaxNamespace.cs
Snowflake/Ajax/JSResponse.cs
Snowflake/Platform/PlatformInfo.cs

This implements the standard set of Ajax methods as specified in #60

Ajax: A new standard ajax interface

---

Snowflake.Service/Service/Manager/AjaxManager.cs
Snowflake.Service/Service/Server/JsonApiServer.cs
Snowflake.Service/Service/Server/JsonApiWebSocketServer.cs
Snowflake/Ajax/JSResponse.cs
Snowflake/Extensions/HttpListenerContextExts.cs

This pull requests fixes some crucial JSAPI bugs that prevent proper usage of the Ajax GET transport.

JSAPI: AjaxManager GET fixes

---

Snowflake.StandardAjax/StandardAjax.Game.cs
Snowflake.StandardAjax/StandardAjax.System.cs

Renames the GetGamesForPlatform to GetGamesByPlatform

JSAPI: GetGamesForPlatform -> GetGamesByPlatform

---

Snowflake.API/Plugin/IBasePlugin.cs
Snowflake/Plugin/BasePlugin.cs

Provides an exit points for plugin.

Plugin: Make IBasePlugin inherit from IDisposable (Fixes #127)

---

.travis.yml

Use docker infrastructure when building on Travis-CI

travis-ci: Use docker infrastructure to build

---

Snowflake.StandardAjax/StandardAjax.Game.cs

JSAPI: Make SetFlagValues return all the flag values instead of echoing the input. (#131)

---

Snowflake.Events/CoreEvents/Game/GameStartEventArgs.cs
Snowflake.StandardAjax/StandardAjax.Controller.cs
Snowflake.StandardAjax/StandardAjax.Game.cs
Snowflake/Ajax/JSRequest.cs

* Fixes 1 NRE
* Make Ajax methods that used to return a status string now return a usable object
* Use a TryGetValue when getting a Ajax method parameter

Maintenance: Bugfixes

---

Snowflake.Events/Snowflake.Events.nuspec
Snowflake.InputManager.DirectInput/Snowflake.InputManager.DirectInput.nuspec
Snowflake.Tests/Snowflake.Tests.nuspec
Snowflake.sln
Snowflake/Snowflake.nuspec

Pulling Snowflake from NuGet should now pull Snowflake.API as well.

Build: Specify NuGet dependencies

---

Snowflake.Tests/packages.config
appveyor.yml

AppVeyor hasn't been restoring solution packages, I suspect this is because of new behaviour in NuGet 3.1

Tests: Install test packages to Snowflake.Tests as per NuGet 3.1

---

Snowflake.StandardAjax/StandardAjax.System.cs

I guess they were accidentally disabled somehow during #171

StandardAjax.System: Fix system methods

---

Snowflake.Packaging/Installing/InstallManager.cs
Snowflake.Packaging/Program.cs
Snowflake.Packaging/Snowball/Package.cs

Some fixes to snowball before I rewrite the pos completely.

Snowball: Band-aid fixes for snowball

---

.travis.yml
Packaging/Snowball.CLI/Program.cs
Packaging/Snowball.CLI/Snowball.CLI.csproj
Packaging/Snowball.CLI/packages.config
Snowflake.FileSignatures.Package/Snowflake.FileSignatures.Package.csproj
appveyor.yml

* Add support for codecov.io
* Fix builds on travis and mono

Fix CI Services

---

LICENSE
README.md

Will also need to update the readme.

Relicense from Apache 2 to MPL (fixes #230)

---

.travis.yml
src/Snowflake.Support.Windows.InputManager/Snowflake.Support.Windows.InputManager.csproj

Build: Make InputManager build with netstandard1.6

---

src/Snowflake.Framework/JsonConverters/ControllerLayoutConverter.cs
src/Snowflake.Framework/Snowflake.Framework.csproj

ControllerLayoutConverter: Make tuple name explicit

---

.gitignore
.travis.yml
build/build.cake
build/build.sh
src/Snowflake.Framework.Tests.DummyComposable/Snowflake.Framework.Tests.DummyComposable.csproj
src/Snowflake.Framework.Tests.InvalidComposable/Snowflake.Framework.Tests.InvalidComposable.csproj
src/Snowflake.Plugin.Emulators.RetroArch/Snowflake.Plugin.Emulators.RetroArch.csproj
src/Snowflake.Plugin.Scraping.TheGamesDb/Snowflake.Plugin.Scraping.TheGamesDb.csproj
src/Snowflake.Support.Execution.Providers/Snowflake.Support.Execution.Providers.csproj
src/Snowflake.Support.FileSignatures/Snowflake.Support.FileSignatures.csproj
src/Snowflake.Support.PluginManager/Snowflake.Support.PluginManager.csproj
src/Snowflake.Support.Remoting.GraphQl.RootProvider/Snowflake.Support.Remoting.GraphQl.RootProvider.csproj
src/Snowflake.Support.Remoting.GraphQl/Snowflake.Support.Remoting.GraphQl.csproj
src/Snowflake.Support.Scraping.RecordScrapeEngine/Snowflake.Support.Scraping.RecordScrapeEngine.csproj
src/Snowflake.Support.Scraping.RecordTraversers/Snowflake.Support.Scraping.RecordTraversers.csproj
src/Snowflake.Support.ShiragameProvider/Snowflake.Support.ShiragameProvider.csproj
src/Snowflake.Support.StoneProvider/Snowflake.Support.StoneProvider.csproj
src/Snowflake.Support.StoreProviders/Snowflake.Support.StoreProviders.csproj
src/Snowflake.Support.Windows.InputEnumerators/Snowflake.Support.Windows.InputEnumerators.csproj
src/Snowflake.Support.Windows.InputManager/Snowflake.Support.Windows.InputManager.csproj
src/Snowflake.Tooling.Taskrunner/Snowflake.Tooling.Taskrunner.csproj
src/Snowflake.Tooling.Taskrunner/Tasks/InstallTask/PackageInstaller.cs
src/Snowflake.Tooling.Taskrunner/Tasks/PackTask/ModulePacker.cs

Also changes the padding scheme to Pkcs1 for package signing as Pss is not supported on Linux for RSACryptoProvider

Build: Make changes so CAKE script will build on Linux.

---

src/Snowflake.Framework.Tests.DummyComposable/Snowflake.Framework.Tests.DummyComposable.csproj
src/Snowflake.Framework.Tests.InvalidComposable/Snowflake.Framework.Tests.InvalidComposable.csproj
src/Snowflake.Plugin.Emulators.RetroArch/Snowflake.Plugin.Emulators.RetroArch.csproj
src/Snowflake.Plugin.Scraping.TheGamesDb/Snowflake.Plugin.Scraping.TheGamesDb.csproj
src/Snowflake.Support.Execution.Providers/Snowflake.Support.Execution.Providers.csproj
src/Snowflake.Support.FileSignatures/Snowflake.Support.FileSignatures.csproj
src/Snowflake.Support.PluginManager/Snowflake.Support.PluginManager.csproj
src/Snowflake.Support.Remoting.GraphQl.RootProvider/Snowflake.Support.Remoting.GraphQl.RootProvider.csproj
src/Snowflake.Support.Remoting.GraphQl/Snowflake.Support.Remoting.GraphQl.csproj
src/Snowflake.Support.Remoting.GraphQl/Types/Execution/EmulatorTaskResultGraphType.cs
src/Snowflake.Support.Remoting.GraphQl/Types/GuidGraphType.cs
src/Snowflake.Support.Remoting.GraphQl/Types/Values/PrimitiveGraphType.cs
src/Snowflake.Support.Scraping.RecordScrapeEngine/Snowflake.Support.Scraping.RecordScrapeEngine.csproj
src/Snowflake.Support.Scraping.RecordTraversers/Snowflake.Support.Scraping.RecordTraversers.csproj
src/Snowflake.Support.ShiragameProvider/Snowflake.Support.ShiragameProvider.csproj
src/Snowflake.Support.StoneProvider/Snowflake.Support.StoneProvider.csproj
src/Snowflake.Support.StoreProviders/Snowflake.Support.StoreProviders.csproj
src/Snowflake.Support.Windows.InputEnumerators/Snowflake.Support.Windows.InputEnumerators.csproj
src/Snowflake.Support.Windows.InputManager/Snowflake.Support.Windows.InputManager.csproj
src/Snowflake.Tooling.Taskrunner/Snowflake.Tooling.Taskrunner.csproj
src/Snowflake.Tooling.Taskrunner/Tasks/InstallTask/PackageInstaller.cs
src/Snowflake.Tooling.Taskrunner/Tasks/PackTask/AssemblyTreeShaker.cs
src/Snowflake.Tooling.Taskrunner/Tasks/PackTask/ModulePacker.cs
src/Snowflake.Tooling.Taskrunner/Tasks/PackTask/PackTaskArguments.cs

Shakes away dependencies from `Snowflake.Framework`.

Tree shaking packer

---

src/Snowflake.Framework.Tests/Scraping/ScraperIntegrationTests.cs

Disable the broken TGDB test due to new API.

Tests: Disable TGDB Tests for now

---

src/Snowflake.Framework.Primitives/Snowflake.Framework.Primitives.csproj
src/Snowflake.Framework.Services/Snowflake.Framework.Services.csproj
src/Snowflake.Framework.Tests/Snowflake.Framework.Tests.csproj
src/Snowflake.Framework/Snowflake.Framework.csproj
src/Snowflake.Support.GraphQLFrameworkQueries/Types/Model/GameFileExtensionGraphType.cs
src/Snowflake.Support.StoreProviders/Snowflake.Support.StoreProviders.csproj

Also update Nullable Reference Types options

Update dependencies at once

---

azure-setup.yml
build/Build.cs
build/Snowflake.Tooling.BuildScript.csproj
src/Snowflake.Framework.Primitives/Snowflake.Framework.Primitives.csproj
src/Snowflake.Framework.Remoting/GraphQL/Schema/GraphQLExecuterProvider.cs
src/Snowflake.Framework.Remoting/Snowflake.Framework.Remoting.csproj
src/Snowflake.Framework.Services/Snowflake.Framework.Services.csproj
src/Snowflake.Framework.Tests/GraphQl/QueryBuilderTests.cs
src/Snowflake.Framework.Tests/Model/ControllerElementMappingsStoreTests.cs
src/Snowflake.Framework.Tests/Snowflake.Framework.Tests.csproj
src/Snowflake.Framework/Snowflake.Framework.csproj
src/Snowflake.Plugin.Debug.GraphQLVisualizers/Snowflake.Plugin.Debug.GraphQLVisualizers.csproj
src/Snowflake.Support.GraphQLFrameworkQueries/Snowflake.Support.GraphQLFrameworkQueries.csproj
src/Snowflake.Support.StoreProviders/Snowflake.Support.StoreProviders.csproj
src/Snowflake.Support.Windows.InputManager/Snowflake.Support.Windows.InputManager.csproj
src/Snowflake.Tooling.Taskrunner/Snowflake.Tooling.Taskrunner.csproj
src/Snowflake.Tooling.Taskrunner/Tasks/ArgumentDisplayTask/ArgumentDisplayTaskRunner.cs
src/Snowflake.Tooling.Taskrunner/Tasks/HelpTask/HelpTaskRunner.cs
src/Snowflake.Tooling.Taskrunner/Tasks/TaskListTask/TaskListTaskRunner.cs

* Updates dependencies
* Build on .NET 3.0 Preview 4
* Target `netcoreapp2.2` for `dotnet-snowflake` taskrunner as per changes described in https://github.com/dotnet/sdk/issues/3115
* Test separately from build artifacts on Azure
* Use DotNetCoreInstaller@1 to install .NET Core
* Fix some test behavior

Build: Update Dependencies

---

src/Snowflake.Framework/Snowflake.Framework.csproj
src/Snowflake.Support.StoneProvider/StoneProvider.cs

Update Stone Definitions to 9.1.0

---

azure-pack.yml
azure-setup.yml
azure-test.yml
lgtm.yml
src/Snowflake.Framework.Services/Snowflake.Framework.Services.csproj
src/Snowflake.Framework/Configuration/Serialization/ConfigurationTraversalContext.cs
src/Snowflake.Framework/Filesystem/Directory.cs
src/Snowflake.Framework/Installation/Tasks/ExtractZipTask.cs
src/Snowflake.Framework/Loader/ServiceProvider.cs
src/Snowflake.Framework/Romfile/Tokenizer/StructuredFilenameTokenizer.cs
src/Snowflake.Plugin.Debug.GraphQLVisualizers/Snowflake.Plugin.Debug.GraphQLVisualizers.csproj
src/global.json

Update .NET Core version and GraphQL Dependencies

---

src/Snowflake.Framework.Tests/Configuration/InputMapperTests.cs
src/Snowflake.Framework.Tests/Extensibility/PluginTests.cs
src/Snowflake.Framework.Tests/Model/ControllerElementMappingsStoreTests.cs
src/Snowflake.Framework.Tests/Model/GameLibraryIntegrationTests.cs
src/Snowflake.Framework.Tests/Scraping/ScrapeContextTests.cs
src/Snowflake.Framework/Extensibility/Provisioning/Standalone/EmptyPluginConfigurationStore.cs
src/Snowflake.Support.GraphQLFrameworkQueries/Queries/InstallationQueryBuilder.cs
src/Snowflake.Support.GraphQLFrameworkQueries/Queries/OrchestrationQueryBuilder.cs

Tests: Add some additional tests

---

src/Snowflake.Framework/Configuration/Serialization/Serializers/Implementations/SimpleJsonConfigurationSerializer.cs
src/Snowflake.Support.GraphQL.FrameworkQueries/Mutations/Game/GameMutations.cs
src/Snowflake.Support.GraphQL.FrameworkQueries/Mutations/Installation/CreateValidationInput.cs
src/Snowflake.Support.GraphQL.FrameworkQueries/Mutations/Installation/InstallationCancelledPayload.cs
src/Snowflake.Support.GraphQL.FrameworkQueries/Mutations/Installation/InstallationCompletePayload.cs
src/Snowflake.Support.GraphQL.FrameworkQueries/Queries/Filesystem/FilesystemQueries.cs
src/nuget.config

also some small styling cleanups

GraphQL: remove myget-graphql-dotnet dependency
