SnowflakePowered/snowflake

appveyor.yml
Even if nuget push fails, the build will still succeed.
=> Build: Fix appveyor build caused by faulty nuget push

Snowflake.API/Emulator/Configuration/IConfigurationFlag.cs, Snowflake/Emulator/Configuration/ConfigurationFlag.cs
This implements a maximum and minimum threshold for integer type configuration flags.
=> [BREAKING] Implement RangeMax and RangeMin for IConfigurationFlag (#45)

Snowflake.Events/ServiceEvents/CoreShutdownEventArgs.cs, Snowflake.Events/Snowflake.Events.csproj, Snowflake.Events/SnowflakeEventSource.ServiceEvents.cs, Snowflake.Tests/Events/SnowflakeEventSourceTests.cs
This doesn't break API as the events are implemented separately as a static instance.
=> Events: Add CoreShutdownEvent

Snowflake.API/Scraper/IScraper.cs, Snowflake.Service/Service/ScrapeService.cs, Snowflake.Tests/Fakes/FakeScraper.cs, Snowflake/Scraper/BaseScraper.cs
Provides extensions to the IScraper interface to allow for paramterized identifier metadata scrape queries.
=> BREAKING Scraper: Parameterized Identifiers (#62)

Snowflake.API/Snowflake.API.nuspec, Snowflake.Events/Snowflake.Events.nuspec, Snowflake.InputManager.DirectInput/Snowflake.InputManager.DirectInput.nuspec, Snowflake.Tests/Properties/AssemblyInfo.cs, Snowflake.Tests/Snowflake.Tests.csproj, Snowflake.Tests/Snowflake.Tests.nuspec, appveyor.yml
The Events, InputManager and Tests assemblies will be published to the MyGet feed as part of the appveyor build process.
=> Build: Add and publish nupkgs for Events, InputManager and Tests

Snowflake.API/Ajax/AjaxMethodParameterAttribute.cs, Snowflake.API/Ajax/IBaseAjaxNamespace.cs, Snowflake.API/Ajax/IJSMethod.cs, Snowflake.API/Snowflake.API.csproj, Snowflake.Service/Service/Manager/AjaxManager.cs, Snowflake/Ajax/BaseAjaxNamespace.cs, Snowflake/Ajax/JSMethod.cs, Snowflake/Ajax/JSResponse.cs, Snowflake/Snowflake.csproj
This adds the 'request' and 'type' keys in the JSON body. The request is the IJSRequest that prompted the reply, and the type key indicates that the response was prompted from calling a method. 
This works in conjunction with #75 by allowing types of JS messages other than the result of a method call.
=> JSAPI: Implement required Javascript Parameters and JSON response metadata

Snowflake.StandardAjax/StandardAjax.Game.cs
This adds an Ajax method that sorts all games present by the platform of each game instead of in a flat array.
=> StandardAjax: Add a method to get all games sorted by platform

Snowflake.Service/Service/Manager/AjaxManager.cs
Instead of returning a `KeyNotFoundException`, provide a simple failed response indicating the absent method in which namespace.
=> JSAPI: Add explicit error message if method not found

Snowflake.StandardAjax/StandardAjax.Game.cs
This returns a Javascript array of flag values. Instead of having to query multiple times for all values this groups it together in a single request.
=> StandardAjax: Implement a method to get all flag values

Snowflake.StandardAjax/StandardAjax.Game.cs
If the game info contains unicode characters, the encoding will fail. Therefore, simply pass the raw, unencoded json as a parameter.
=> StandardAjax: Pass raw game info json instead of encoded

Platforms/NINTENDO_NES.platform, Platforms/NINTENDO_SNES.platform, Snowflake.API/Emulator/IEmulatorAssembly.cs, Snowflake.API/Information/IInfo.cs, Snowflake.Service/Service/CoreService.cs, Snowflake.Service/Service/Manager/EmulatorAssembliesManager.cs, Snowflake.Service/Service/ScrapeService.cs, Snowflake.StandardAjax/StandardAjax.Game.cs, Snowflake.Tests/Fakes/FakeEmulatorAssembly.cs, Snowflake.Tests/Fakes/FakeGameInfo.cs, Snowflake.Tests/Fakes/FakePlatformInfo.cs, Snowflake.Tests/Platform/PlatformInfoTests.cs, Snowflake/Controller/ControllerPortsDatabase.cs, Snowflake/Emulator/EmulatorAssembly.cs, Snowflake/Game/GameDatabase.cs, Snowflake/Information/Info.cs, Snowflake/Platform/PlatformInfo.cs, Snowflake/Platform/PlatformPreferencesDatabase.cs
This renames all UpperCamelCased references including the string 'Id' to 'ID'. 
> An I.D. (identifier) property or variable name shall use the form 'ID' if the name is UpperCamelCased according to other conventions. If the name of the property or variable is in the local scope and thus is lowerCamelCased, the name shall use the form 'Id'.
=> Normalize references to 'Id' to 'ID'

Snowflake.API/Service/HttpServer/BaseHttpServer.cs, Snowflake.API/Service/ICoreService.cs, Snowflake.API/Service/JSWebSocketServer/IJSWebSocketServer.cs, Snowflake.API/Service/Manager/IServerManager.cs, Snowflake.API/Snowflake.API.csproj, Snowflake.Core.Init/Form1.cs, Snowflake.Events/ServiceEvents/ServerStartEventArgs.cs, Snowflake.Events/ServiceEvents/ServerStopEventArgs.cs, Snowflake.Events/Snowflake.Events.csproj, Snowflake.Events/SnowflakeEventSource.ServiceEvents.cs, Snowflake.Service/Service/CoreService.cs, Snowflake.Service/Service/Manager/ServerManager.cs, Snowflake.Service/Service/Server/JsonApiWebSocketServer.cs, Snowflake.Service/Snowflake.Service.csproj, Snowflake.Tests/Fakes/FakeCoreService.cs, Snowflake.Tests/Service/HttpServer/BaseHttpServerTests.cs
This adds the `IServerManager` interface to CoreService and no longer requires a web server to be coupled tightly to the `ICoreService` interface. This is a breaking change and any methods that call upon the servers directly will have to be modified to access the server through `ICoreService.ServerManager`.
=> [WIP] BREAKING CoreService: Abstract away servers in a collection (#92)

Snowflake.API/Controller/IControllerPortsDatabase.cs, Snowflake.API/Controller/IControllerProfile.cs, Snowflake.API/Service/ICoreService.cs, Snowflake.Core.Init/Form1.cs, Snowflake.Service/Service/CoreService.cs, Snowflake.Service/Snowflake.Service.csproj, Snowflake.StandardAjax/StandardAjax.Controller.cs, Snowflake.Tests/Fakes/FakeControllerProfile.cs, Snowflake.Tests/Fakes/FakeCoreService.cs, Snowflake/Controller/ControllerProfile.cs
This implements the following API relating to controllers and input.
- `Controller.GetProfiles(controller)`
Gets all the input profile/configurations for the specified controller ID for all registered devices
- `Controller.GetProfileForDevice(controller, device)`
Gets the controller input profile for the given device and controller
- `Controller.SetInputConfiguration(inputconfig, controller, device) //todo extend to create input configurations`
Sets the input configuration data for a given device and controller. The API thus can not modify the controller profiles besides the input configuration. A job todo is to extend this API such that it can allow creation of input profiles from scratch. Input configuration is passed as a JSON object with the controller button ID as the key, and the …
=> Controller Ajax API (#88)

Platforms/NINTENDO_NES.platform, Platforms/NINTENDO_SNES.platform, Snowflake.API/Platform/IPlatformDefaults.cs, Snowflake.API/Platform/IPlatformInfo.cs, Snowflake.API/Platform/IPlatformPreferenceDatabase.cs, Snowflake.Service/Extensions/PlatformExts.cs, Snowflake.Service/Service/CoreService.cs, Snowflake.Service/Service/ScrapeService.cs, Snowflake.StandardAjax/StandardAjax.Game.cs, Snowflake/Platform/PlatformDefaults.cs, Snowflake/Platform/PlatformInfo.cs, Snowflake/Platform/PlatformPreferencesDatabase.cs, Snowflake/Snowflake.csproj, Snowflake/app.config
This PR cleans up usage of the PlatformDefaults and PlatformPreferencesDatabase. 
PlatformDefaults are now only used when returning an object form the PlatformPreferencesDatabase. The Platform definition no longer stores it's own set of defaults, instead they are inferred from currently available plugins and stored by snowflake the first time a platform is installed. 
This breaks the IPlatformInfo interface and any classes that utilized the PlatformDefaults property will no longer function.
=> BREAKING Improve PlatformDefaults and PlatformDefaultsDatabase (#103)

Snowflake.Service/Service/CoreService.cs, Snowflake.Service/Service/Manager/AjaxManager.cs, Snowflake.Service/Service/Manager/EmulatorAssembliesManager.cs, Snowflake.Service/Service/Manager/PluginManager.cs, Snowflake.StandardAjax/StandardAjax.Game.cs
This PR fixes issue #109 and returns select flags by their index rather than value. Emulator bridges must use this index to grab the correct flag. This will break the select value if the bridge plugin maintainer prepends new select values instead of appending but this is the responsibility of the plugin maintainer to ensure backwards compatibility.
=> Switch to index-based select values (#109)

Snowflake.API/Controller/ControllerProfileType.cs, Snowflake.API/Utility/BaseDatabase.cs, Snowflake/Controller/ControllerPortsDatabase.cs, Snowflake/Controller/ControllerProfile.cs, Snowflake/Controller/ControllerProfileStore.cs, Snowflake/Emulator/Configuration/ConfigurationFlagStore.cs, Snowflake/Emulator/EmulatorBridge.cs, Snowflake/Game/GameDatabase.cs, Snowflake/Platform/PlatformPreferencesDatabase.cs
This PR makes the following changes
* ControllerProfileStore implements a null profile for controllers not recognized by a system and unfilled ports
* BaseDatabase moves from a single connection model to a multiple connection model that returns a new connection every time. This prevents any InvalidOperationExceptions when accessing the database
=> Prevent NREs due to invalid access to stores and database

Snowflake.API/Snowflake.API.csproj, Snowflake.API/Utility/BaseDatabase.cs, Snowflake.Core.Init/App.config, Snowflake.Core.Init/Form1.cs, Snowflake.Service/app.config, Snowflake.StandardAjax/Snowflake.StandardAjax.csproj, Snowflake.StandardAjax/app.config, Snowflake.Tests/Snowflake.Tests.csproj, Snowflake.Tests/app.config, Snowflake/Emulator/Configuration/ConfigurationFlagStore.cs, Snowflake/Emulator/Configuration/ConfigurationFlagStore.cs.orig, Snowflake/app.config, Snowflake/packages.config
Rather than a JSON file for every game, this commit switches ConfigurationFlagStore to use a SQLite database as a KeyValue store. This is more reliable and SQLite is able to handle concurrent writes better than just dumping JSON data into a file.
=> ConfigurationFlagStore: Use a SQLite database to store flags

Snowflake.StandardAjax/StandardAjax.Controller.cs
This allows snowflake.js to get all device ports at once
=> StandardAjax.Controller: Implement GetDeviceInPorts

Snowflake.Events/Snowflake.Events.csproj, Snowflake.Events/SnowflakeEventManager.cs, Snowflake.Events/StandardEvents.cs, Snowflake.Tests/Events/SnowflakeEventManagerTests.cs, Snowflake.Tests/Events/StandardEventsTests.cs, Snowflake.Tests/Snowflake.Tests.csproj
This PR renames SnowflakeEventSource to StandardEvents for clarity and re-adds tests for StandardEvents.
=> [Events] SnowflakeEventSource improvements

Snowflake.API/Plugin/Configuration/IPluginConfigOption.cs, Snowflake.API/Plugin/Configuration/IPluginConfiguration.cs, Snowflake.API/Plugin/Configuration/IPluginSelectOption.cs, Snowflake.API/Plugin/Configuration/PluginOptionType.cs, Snowflake.API/Plugin/IBasePlugin.cs, Snowflake.API/Snowflake.API.csproj, Snowflake/NLog.config, Snowflake/NLog.xsd, Snowflake/Plugin/BasePlugin.cs, Snowflake/Plugin/YamlConfiguration.cs, Snowflake/Snowflake.csproj, Snowflake/packages.config
This PR adds a Logger object to allows plugins to efficiently log messages. It also separates IPluginConfiguration and new related APIs to the Plugin.Configuration namespace, breaking any plugin that uses IPluginConfiguration.
=> BasePlugin: Add more utilities for plugins to utilise

Snowflake.API/Emulator/Input/IKeyboardMapping.cs, Snowflake/Emulator/Input/KeyboardMapping.cs
This breaks compatibility with EmulatorBridge plugins that now must accommodate for the new IKeyboardMapping keys
- MOUSE_X_LEFT
- MOUSE_X_RIGHT
- MOUSE_Y_UP
- MOUSE_Y_DOWN
Todo
------
=> [BREAKING] IKeyboardMapping: Add mouse support to mappingData Fixes (#136)

Snowflake.Service/Service/Manager/EmulatorAssembliesManager.cs, Snowflake/Emulator/EmulatorAssembly.cs
This removes the final required dependency on SharpYaml except for YamlConfiguration.
The schema is the same, however the filename shall be .emulatordef and be in JSON.
=> EmulatorAssembly: Use JSON rather than YAML emulator files

Snowflake.API/Emulator/IEmulatorBridge.cs, Snowflake/Emulator/EmulatorBridge.cs
**This is an API level break; all emulator bridge plugins that override the default CompileConfiguration methods will require small changes before it builds again**
This was a giant oversight in the original design of the CompileConfiguration API; the IGameInfo object is never passed to the method, so the API is not aware of which game it is compiling configuration for. While this may be redundant, without this, there is no way to do flag-aware controller compilation, such as required for Dolphin's Wiimote attachments. Most emulator bridges will never need to be aware of the IGameInfo object it's called with, but for those that do, the IGameInfo object is now passed through every single overload to ensure all bridges will have access to this info no matter how far up the chain they are …
=> BREAKING IEmulatorBridge: Pass IGameInfo for the game when compiling controller config

Snowflake.Packaging/Snowball/Package.cs
Previously it looked for snowflake.json instead.
=> Package.cs: Get embedded snowball.json properly

Snowflake.API/Emulator/EmulatorInstanceState.cs, Snowflake.API/Emulator/IEmulatorBridge.cs, Snowflake.API/Emulator/IEmulatorInstance.cs, Snowflake.API/Service/Manager/IEmulatorBridgeManager.cs, Snowflake.API/Service/Manager/IEmulatorInstanceManager.cs, Snowflake.API/Snowflake.API.csproj, Snowflake.Service/Service/Manager/EmulatorInstanceManager.cs, Snowflake.Service/Snowflake.Service.csproj, Snowflake.StandardAjax/StandardAjax.Game.cs, Snowflake/Emulator/EmulatorBridge.cs, Snowflake/Emulator/ProcessEmulatorInstance.cs, Snowflake/Snowflake.csproj
This Pull Request is a breaking change to the **IEmulatorBridge** API and adds 3 new interfaces
**IEmulatorInstanceManager** is now in charge of the lifetime of an emulator, rather than the bridge plugin handling process start, etc. 
**IEmulatorInstance** represents an instance of an emulator. This is used to control the lifetime of the emulator process, and can represent anything from an external process, or an internal DLL call. It is meant to be overridden and reimplemented by different bridge plugins to suit their needs if needed.
**EmulatorInstanceState** represents the state of an instance of an emulator.
`IEmulatorBridge.StartRom` has been replaced by `IEmulatorBridge.CreateInstance`, which is used to set up the instance without actually starting the ROM. That responsibility now …
=> [WIP BREAKING] Instance-based emulator bridges (Fixes #188)

Snowflake.Service/Service/Manager/PluginManager.cs, Snowflake.Shell.Windows/Program.cs, Snowflake/Plugin/BasePlugin.cs
This makes Snowflake load assemblies from the plugin data paths of plugins, so that dependencies can be included in snowballs without leading to overwriting of assemblies in the plugin folder and clogging the folder up with non-plugin assemblies. 
Manually, symlink, or with a script, copy any dependencies into your plugin data folder. They will be loaded on-demand into the default AppDomain prior to the initialization of the entry-point class, and once loaded, .NET takes care of dependency resolution.
=> PluginManager: Preload plugin dependencies from plugin data path (fixes #205)

.travis.yml, src/Snowflake.Framework.Persistence/SqliteDatabase.cs, src/Snowflake.Framework.Primitives/Records/File/IFileLibrary.cs, src/Snowflake.Framework.Primitives/Records/File/IFileRecord.cs, src/Snowflake.Framework.Primitives/Records/IRecordLibrary.cs, src/Snowflake.Framework.Tests/Records/SqliteFileLibraryTests.cs, src/Snowflake.Framework.Tests/Records/SqliteGameLibraryTests.cs, src/Snowflake.Framework/Records/File/FileRecord.cs, src/Snowflake.Framework/Records/File/SqliteFileLibrary.cs, src/Snowflake.Framework/Records/Game/GameRecord.cs, src/Snowflake.Framework/Records/Game/SqliteGameLibrary.cs, src/Snowflake.Framework/Records/RecordLibrary.cs, src/Snowflake.Framework/Records/RecordLibraryJunction.cs, src/Snowflake.Framework/Records/SqliteRecordLibrary.cs, src/Snowflake.Framework/Scraper/ScrapeEngine.cs, src/Snowflake.Support.Caching.KeyedImageCache/KeyedImageCache.cs, src/Snowflake.Support.Remoting/Resources/Games/GameFilesLibraryRoot.cs
Uses a junction table rather than an explicit record column to store the relation between Games and Files. `FileRecord`s now have zero dependence on `GameRecord`, and constructors relating to the creation of FileRecords with a linked record have been removed.
=> Remove Reliance on GameLibrary from FileLibrary

src/Snowflake.Framework.Primitives/Input/Controller/ControllerElement.cs, src/Snowflake.Framework.Primitives/Input/Controller/ControllerElementType.cs, src/Snowflake.Framework.Primitives/Input/Controller/IControllerElementCollection.cs, src/Snowflake.Framework/Input/Controller/ControllerElementCollection.cs
Stone becomes stable as of 7.1.0, introducing a breaking change from 7.0.0-alpha.12 (legal due to unstable tag), with the Gyroscope ControllerElement.
This does not pull the 7.1.0 definitions however, only updating the internal Stone API. 7.0.0-alpha.12 definitions are still in use for now.
Hopefully should not cause any database issues.
=> Input: Add support for the Gyroscope ControllerElement as of Stone 7.1.1

azure-codecov.yml, azure-pipelines.yml, azure-setup.yml, build/Build.cs, src/Snowflake.Framework.Tests/GraphQl/QueryBuilderTests.cs
Attempting to fix the test without having to remove it completely.
Since calling the method directly through the resolver tests seem to work, there must be something going wrong with the executor in the Azure environment.
Confirmed not a Linux problem, as the issue does not occur on Fedora 29 either.
=> Tests: Disable GraphQLFieldQuery_Test()

azure-pack.yml, azure-setup.yml, azure-test.yml, lgtm.yml, src/Snowflake.Framework.Primitives/Model/Game/IGame.cs, src/Snowflake.Framework.Primitives/Model/Game/IGameLibrary.cs, src/Snowflake.Framework.Tests/Model/GameLibraryIntegrationTests.cs, src/Snowflake.Framework/Model/Game/Game.cs, src/Snowflake.Framework/Model/Game/GameLibrary.cs, src/global.json
For some reason it doesn't like the signature `T? Fn<T>() where T: class, IInterface` anymore, so nullable refs for those have been removed.
=> Build: make changes to support .NET Core 3.0-preview6

src/Snowflake.Framework.Primitives/Configuration/IConfigurationValueCollection.cs, src/Snowflake.Framework.Primitives/Model/Records/File/ImageMetadataKeys.cs, src/Snowflake.Framework.Primitives/Model/Records/File/ImageTypes.cs, src/Snowflake.Framework.Tests.Input.Windows/Snowflake.Framework.Tests.Input.Windows.csproj, src/Snowflake.Framework.Tests/Configuration/ConfigurationCollectionTests.cs, src/Snowflake.Framework.Tests/Model/ConfigurationStoreTests.cs, src/Snowflake.Framework/Configuration/ConfigurationValueCollection.cs, src/Snowflake.Framework/Model/Database/ConfigurationCollectionStore.Async.cs, src/Snowflake.Framework/Model/Database/ConfigurationCollectionStore.cs, src/Snowflake.Framework/Model/Database/PluginConfigurationStore.Async.cs, src/Snowflake.Support.InputEnumerators.Windows/Snowflake.Support.InputEnumerators.Windows.csproj
* Adds a `this[Guid]` indexer for `IConfigurationValueCollection` to allow this.
* Works in O(1) by keeping parallel dictionaries, also has the effect of ensuring config values are unique.
* Moves `ImageMetadataKeys` to `Snowflake.Model.Records.File` namespace
* Some tests for config deletion.
=> ConfigurationCollectionStore: Micro-optimization for ConfigurationCollectionStore

src/Snowflake.Framework.Primitives/Input/Device/IDeviceCapabilityLabels.cs, src/Snowflake.Framework.Primitives/Input/Device/IInputDriverInstance.cs, src/Snowflake.Framework.Tests/Input/LabelsTests.cs, src/Snowflake.Framework/Input/Device/DefaultDeviceCapabilityLabels.cs, src/Snowflake.Framework/Input/Device/DictionaryDeviceCapabilityLabels.cs, src/Snowflake.Framework/Input/Device/DirectInputDeviceInstance.cs, src/Snowflake.Framework/Input/Device/KeyboardDeviceInstance.cs, src/Snowflake.Framework/Input/Device/PassthroughDeviceInstance.cs, src/Snowflake.Framework/Input/Device/XInputDeviceInstance.cs, src/Snowflake.Framework/Snowflake.Framework.xml, src/Snowflake.Support.GraphQLFrameworkQueries/Types/InputDevice/DeviceCapabilityLabelKeyValuePairGraphType.cs, src/Snowflake.Support.GraphQLFrameworkQueries/Types/InputDevice/DeviceCapabilityLabelsGraphType.cs, src/Snowflake.Support.GraphQLFrameworkQueries/Types/InputDevice/InputDeviceInstanceGraphType.cs, src/Snowflake.Support.InputEnumerators.Windows/WindowsDeviceEnumerator.cs
Addresses #593 partially by providing a markup agnostic API for capability labels
=> Device: add API for capability labels
